"""
ComfyUI-VideoDescription
Video description and storyboard custom nodes for ComfyUI
"""

from .video_nodes import (
    NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .storyboard_nodes import (
    NODE_CLASS_MAPPINGS as STORYBOARD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS,
)
from .utility_nodes import (
    NODE_CLASS_MAPPINGS as UTILITY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_nodes import (
    NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .controlnet_nodes import (
    NODE_CLASS_MAPPINGS as CONTROLNET_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CONTROLNET_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lora_nodes import (
    NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS,
)

# Merge node mappings
NODE_CLASS_MAPPINGS = {
    **VIDEO_NODE_CLASS_MAPPINGS,       # IXIWORKS/Video
    **STORYBOARD_NODE_CLASS_MAPPINGS,  # IXIWORKS/StoryBoard
    **UTILITY_NODE_CLASS_MAPPINGS,     # IXIWORKS/Utils
    **IMAGE_NODE_CLASS_MAPPINGS,       # IXIWORKS/Image
    **CONTROLNET_NODE_CLASS_MAPPINGS,  # IXIWORKS/ControlNet
    **LORA_NODE_CLASS_MAPPINGS,        # IXIWORKS/LoRA
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
    **STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS,
    **UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **CONTROLNET_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
